server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

jwt:
  secret: ${JWT_SECRET}


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/**

        - id: train-service
          uri: ${TRAIN_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/train/**

        - id: booking-service
          uri: ${BOOKING_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/booking/**

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/payments/**
