server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://ep-frosty-bird-a1i1lnsi-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?currentSchema=train_service&sslmode=require&channelBinding=require


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true